Repository SwanHubX/SwanLab-Dashboard, pull requests merged in 2024-06, with the labels that each got.

#11 update debug print and version
  .vscode/settings.json
  swanboard/callback.py
  swanboard/package.json
Labels: bug

#17 Feature/some updates
  test/start_server.py
  vue/index.html
  vue/src/assets/logo.ico
  vue/src/assets/logo.png
  vue/src/assets/swanlab.svg
  vue/src/i18n/en-US/experiment.json5
  vue/src/i18n/zh-CN/experiment.json5
  vue/src/views/experiment/pages/environment/pages/EnvIndex.vue
Labels: enhancement, refactor

#14 update link
  pyproject.toml
  swanboard/package.json
  test/start_server.py
  vue/index.html
  vue/src/assets/logo.ico
  vue/src/assets/logo.png
  vue/src/assets/swanlab.svg
  vue/src/i18n/en-US/experiment.json5
  vue/src/i18n/zh-CN/experiment.json5
  vue/src/layouts/main/components/HeaderBar.vue
  vue/src/views/experiment/pages/environment/pages/EnvIndex.vue
Labels: documentation

#19 feat: replace swanlab with swankit
  requirements-dev.txt
  requirements.txt
  swanboard/app.py
  swanboard/callback.py
  swanboard/controller/experiment.py
  swanboard/controller/project.py
  swanboard/db/model.py
  swanboard/db/models/experiments.py
  swanboard/db/models/projects.py
  swanboard/middleware/common.py
  swanboard/run/run.py
  swanboard/run/utils.py
  swanboard/settings.py
  swanboard/utils/__init__.py
  swanboard/utils/log.py
  swanboard/utils/package.py
Labels: enhancement

#20 Feature/pytest
  swanboard/controller/experiment.py
  swanboard/utils/font.py
  swanboard/utils/time.py
  test/config/config.json
  test/config/load.yaml
  test/create_error_chart.py
  test/create_experiment.py
  test/start_server.py
  test/unit/conftest.py
  test/unit/db/models.py
  test/unit/db/pytest_connect.py
  test/unit/pytest_example.py
  test/unit/server/controller/utils/utils.py
  test/unit/utils/pytest_file.py
  test/use_swanlog.py
  tutils/__init__.py
  tutils/config.py
  tutils/env.py
  tutils/parse.py
  tutils/setup.py
  tutils/utils.py
Labels: enhancement

#22 V0.1.2 beta4
  requirements.txt
  swanboard/controller/experiment.py
  swanboard/db/model.py
  swanboard/db/models/experiments.py
  swanboard/package.json
  swanboard/utils/__init__.py
  swanboard/utils/time.py
Labels: enhancement, new version

#24 new version
  requirements.txt
  swanboard/package.json
Labels: new version

#25 fix: connect error
  swanboard/package.json
  swanboard/run/run.py
Labels: bug

#26 Update ErrorWrap.vue
  vue/src/views/error/components/ErrorWrap.vue
Labels: refactor

#27 refactor: connect error
  swanboard/package.json
  swanboard/run/run.py
Labels: refactor

#29 Test/utils
  swanboard/utils/package.py
  test/unit/utils/package.py
  test/unit/utils/pytest_font.py
Labels: enhancement

#30 Test/db
  swanboard/db/db_connect.py
  swanboard/db/migrate/__init__.py
  swanboard/db/migrate/chart.py
  swanboard/db/migrate/experiment.py
  swanboard/db/migrate/namespace.py
  swanboard/db/migrate/project.py
  swanboard/db/migrate/tag.py
  test/unit/db/models.py
  test/unit/db/pytest_connect.py
  test/unit/db/pytest_experiment.py
  test/unit/db/pytest_project.py
  test/unit/db/pytest_swanmodel.py
  test/unit/setup/mock.py
  tutils/__init__.py
  tutils/env.py
  tutils/mock.py
  tutils/setup.py
Labels: enhancement
