Repository SwanHubX/SwanLab-Dashboard, pull requests merged in 2024-07, with the labels that each got.

#36 Create example.test.js
  vite.config.js
  vitest.config.ts
  vue/test/example.test.js
  vue/test/utils/common.test.js
Labels: refactor

#35 refactor: jsdoc
  vue/src/docs/chart.js
Labels: refactor

#37 fix: create tag folder
  swanboard/db/models/tags.py
Labels: bug

#38 fix time
  requirements-dev.txt
  vue/src/utils/time.js
  vue/src/views/home/HomeView.vue
Labels: bug

#39 Feature/format chart data
  jsconfig.json
  package.json
  vue/docs/chart.js
  vue/docs/setup.js
  vue/src/charts/package/LineChart.vue
  vue/src/docs/index.js
  vue/src/store/modules/chart.js
  vue/src/utils/chart.js
  vue/test/example.test.js
  vue/test/utils/chart.test.js
Labels: enhancement

#41 section layout
  package.json
  test/start_server.py
  vite.config.js
  vue/src/board/ChartsBoard.vue
  vue/src/board/charts.d.js
  vue/src/board/components/SectionsWrapper.vue
  vue/src/board/components/SharedComponent.vue
  vue/src/board/i18n/chart.cn.json
  vue/src/board/i18n/chart.en.json
  vue/src/board/puzzle/ChartPreviewPuzzle.vue
  vue/src/board/puzzle/ChartPuzzle.vue
  vue/src/board/puzzle/SectionPuzzle.vue
  vue/src/board/puzzle/layout/MobileLayout.vue
  vue/src/board/puzzle/layout/StandardLayout.vue
  vue/src/board/utils.js
  vue/src/i18n/en-US/chart.json5
  vue/src/i18n/en-US/common.json
  vue/src/i18n/en-US/common.json5
  vue/src/i18n/en-US/error.json
  vue/src/i18n/en-US/error.json5
  vue/src/i18n/en-US/experiment.json
  vue/src/i18n/en-US/experiment.json5
  vue/src/i18n/en-US/home.json
  vue/src/i18n/en-US/home.json5
  vue/src/i18n/en-US/index.js
  vue/src/i18n/en-US/moment.json
  vue/src/i18n/en-US/moment.json5
  vue/src/i18n/en-US/sider.json
  vue/src/i18n/en-US/sider.json5
  vue/src/i18n/zh-CN/chart.json5
  vue/src/i18n/zh-CN/common.json
  vue/src/i18n/zh-CN/common.json5
  vue/src/i18n/zh-CN/error.json
  vue/src/i18n/zh-CN/error.json5
  vue/src/i18n/zh-CN/experiment.json
  vue/src/i18n/zh-CN/experiment.json5
  vue/src/i18n/zh-CN/home.json
  vue/src/i18n/zh-CN/home.json5
  vue/src/i18n/zh-CN/index.js
  vue/src/i18n/zh-CN/moment.json
  vue/src/i18n/zh-CN/moment.json5
  vue/src/i18n/zh-CN/sider.json
  vue/src/i18n/zh-CN/sider.json5
  vue/src/utils/chart.js
Labels: enhancement

#42 define callback
  vue/src/board/ChartsBoard.vue
  vue/src/board/charts.d.js
Labels: documentation

#43 Feature/section collapse
  swanboard/controller/experiment.py
  swanboard/controller/project.py
  vue/src/board/ChartsBoard.vue
  vue/src/board/components/SectionsWrapper.vue
  vue/src/board/puzzle/SectionPuzzle.vue
Labels: enhancement, refactor

#44 update layout
  .vscode/settings.json
  vue/src/board/ChartsBoard.vue
  vue/src/board/README.md
  vue/src/board/charts.d.js
  vue/src/board/charts/audio/AudioChart.vue
  vue/src/board/charts/image/ImageChart.vue
  vue/src/board/charts/line/LineChart.vue
  vue/src/board/charts/text/TextChart.vue
  vue/src/board/charts/toolkit.js
  vue/src/board/components/SectionsWrapper.vue
  vue/src/board/i18n/en-US/chart.json
  vue/src/board/i18n/zh-CN/chart.json
  vue/src/board/puzzle/ChartPuzzle.vue
  vue/src/board/puzzle/chart/ChartWrapper.vue
  vue/src/board/puzzle/chart/poller.js
  vue/src/board/puzzle/chart/utils.js
  vue/src/board/puzzle/layout/StandardLayout.vue
  vue/src/board/store.js
  vue/src/board/utils.js
  vue/src/i18n/en-US/index.js
  vue/src/i18n/zh-CN/index.js
  vue/src/views/charts/ChartsView.vue
Labels: bug

#45 add ujson
  requirements.txt
  swanboard/package.json
Labels: bug

#46 access api
  swanboard/controller/experiment.py
  swanboard/controller/utils/charts.py
  vue/src/api/chart.js
  vue/src/board/ChartsBoard.vue
  vue/src/board/charts.d.js
  vue/src/board/charts/.components/ChartToolbar.vue
  vue/src/board/charts/error/ErrorChart.vue
  vue/src/board/charts/index.js
  vue/src/board/charts/line/LineChart.vue
  vue/src/board/charts/toolkit.js
  vue/src/board/i18n/en-US/chart.json
  vue/src/board/i18n/zh-CN/chart.json
  vue/src/board/puzzle/SectionPuzzle.vue
  vue/src/board/puzzle/chart/ChartWrapper.vue
  vue/src/board/puzzle/chart/utils.js
  vue/src/board/store.js
  vue/src/utils/chart.js
  vue/src/views/charts/ChartsView.vue
  vue/src/views/charts/components/ChartsPage.vue
  vue/src/views/experiment/pages/chart/ChartPage.vue
  vue/test/utils/chart.test.js
Labels: bug, enhancement

#47 Fixbug/pin and hide
  package.json
  swanboard/controller/project.py
  swanboard/controller/utils/tag.py
  vue/src/utils/chart.js
  vue/test/utils/chart.test.js
Labels: bug, enhancement, refactor

#48 Feat/toolbar
  swanboard/controller/chart.py
  vue/src/board/ChartsBoard.vue
  vue/src/board/charts.d.js
  vue/src/board/charts/.components/ChartToolbar.vue
  vue/src/board/charts/line/LineChart.vue
  vue/src/board/i18n/en-US/chart.json
  vue/src/board/i18n/zh-CN/chart.json
  vue/src/board/puzzle/SectionPuzzle.vue
  vue/src/board/puzzle/layout/StandardLayout.vue
  vue/src/utils/chart.js
  vue/src/views/charts/ChartsView.vue
  vue/src/views/experiment/pages/chart/ChartPage.vue
Labels: bug, enhancement

#49 fix: pinned default to be unfolded
  vue/src/utils/chart.js
  vue/test/utils/chart.test.js
Labels: bug

#50 zoom
  vue/src/board/ChartsBoard.vue
  vue/src/board/charts/.components/ChartToolbar.vue
  vue/src/board/charts/audio/AudioChart.vue
  vue/src/board/charts/error/ErrorChart.vue
  vue/src/board/charts/image/ImageChart.vue
  vue/src/board/charts/line/LineChart.vue
  vue/src/board/charts/text/TextChart.vue
  vue/src/board/charts/toolkit.js
  vue/src/board/i18n/en-US/chart.json
  vue/src/board/i18n/zh-CN/chart.json
  vue/src/board/puzzle/ChartPuzzle.vue
  vue/src/board/puzzle/chart/ChartWrapper.vue
  vue/src/utils/chart.js
  vue/src/views/charts/ChartsView.vue
  vue/src/views/experiment/pages/chart/ChartPage.vue
Labels: enhancement

#51 折线图配置完善
  .vscode/settings.json
  swanboard/controller/utils/charts.py
  vue/src/board/ChartsBoard.vue
  vue/src/board/README.md
  vue/src/board/charts.d.js
  vue/src/board/charts/.components/ChartToolbar.vue
  vue/src/board/charts/audio/AudioChart.vue
  vue/src/board/charts/error/ErrorChart.vue
  vue/src/board/charts/image/ImageChart.vue
  vue/src/board/charts/line/LineChart.vue
  vue/src/board/charts/line/components/G2Line.vue
  vue/src/board/charts/line/components/LineLayout.vue
  vue/src/board/charts/line/components/LineLegends.vue
  vue/src/board/charts/line/components/line.js
  vue/src/board/charts/text/TextChart.vue
  vue/src/board/charts/toolkit.js
  vue/src/board/puzzle/chart/ChartWrapper.vue
  vue/src/board/puzzle/chart/utils.js
  vue/src/board/puzzle/layout/StandardLayout.vue
  vue/src/utils/chart.js
  vue/src/views/charts/ChartsView.vue
  vue/test/utils/chart.test.js
Labels: bug, enhancement

#52 折线图接入tooltip等
  swanboard/controller/experiment.py
  vue/src/board/charts.d.js
  vue/src/board/charts/line/components/G2Line.vue
  vue/src/board/charts/line/components/LineLayout.vue
  vue/src/board/charts/line/components/LineTooltip.vue
  vue/src/board/charts/line/components/line.js
  vue/src/board/puzzle/SectionPuzzle.vue
  vue/src/board/puzzle/layout/StandardLayout.vue
  vue/src/board/store.js
  vue/src/utils/chart.js
  vue/src/views/charts/ChartsView.vue
  vue/src/views/experiment/pages/chart/ChartPage.vue
Labels: documentation

#56 add dependence
  requirements.txt
  swanboard/package.json
Labels: bug
